version: "2"

services:
  postgres:
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  database: {}